repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: rust-fix-unused-imports
        name: Remove unused imports with cargo clippy --fix
        entry: cargo clippy --fix --allow-dirty --allow-staged -- -W unused-imports
        language: system
        types: [rust]

    -   id: rustfmt
        name: Format Rust code with rustfmt
        entry: cargo fmt --all
        language: system
        types: [rust]
