def hello_from_bin() -> str: ...
def read_file(path: str, sheet: str, address: str) -> str: ...
def load_workbook(path: str) -> "Book": ...

class Book:
    path: str
    sheetnames: list[str]

    def __init__(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> list["Sheet"]: ...
    def get_sheet_by_name(self, name: str) -> "Sheet": ...

class Sheet:
    name: str

    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> "Cell" | list[str]: ...
    def cell(self, row: int, column: int) -> "Cell": ...
    def set_value(self, row: int, column: int, value: str) -> None: ...

class Cell:
    def __repr__(self) -> str: ...
    def get_value(self) -> str: ...
    def set_value(self, value: str) -> None: ...
