from typing import Iterator, Optional

def hello_from_bin() -> str: ...
def load_workbook(path: str) -> "Book": ...

class Book:
    path: str
    sheetnames: list[str]

    def __init__(self, path: str = ...) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, key: str) -> "Sheet": ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def index(self, sheet: "Sheet") -> int: ...
    def remove(self, sheet: "Sheet") -> None: ...
    def create_sheet(self, title: str, index: int) -> "Sheet": ...
    def copy(self, path: str) -> None: ...

class Sheet:
    @property
    def name(self) -> str: ...
    def __getitem__(self, key: str) -> "Cell": ...
    def cell(self, row: int, column: int) -> "Cell": ...

class Cell:
    @property
    def value(self) -> Optional[str]: ...
    @value.setter
    def value(self, value: str) -> None: ...

class Xml: ...
class XmlElement: ...
